# Author : Vinod Anbalagan
# Project : DocuNative 
# Filename : generate.py  
# Start Date : 03-12-2026
# Modification Date : 03-12-2026
# Description : generate.py is the brain of the pipeline. It takes three inputs: 
# User question, top-3 retrieved chunks from ChromaDB (from retrieve.py), and model choice.
# Returns: The raw model response string in Markdown delimiter format.

"""
pipeline/generate.py

Sends a question + retrieved chunks to our local C++ llama-server and returns
the raw model response in Markdown delimiter format.

Issue: #15
"""

import requests
from typing import List, Dict, Any

# ---- Configuration ---

# We route everything to port 8080. The model choice (Global vs Earth) is handled 
# by whichever model the user spun up in Terminal 1 via `make server-global` or `make server-earth`.

SERVER_URLS = {
    "Global": "http://localhost:8080/completion",
    "Earth":  "http://localhost:8080/completion",  
}

# Hyperparameters for generation

DEFAULT_MAX_TOKENS = 512    # Limits length to prevent the model from rambling indefinitely.
DEFAULT_TEMPERATURE = 0.1   # Low temperature = highly deterministic/robotic. Best for factual QA!

# ---- Prompt Template ---
# Primary defense against hallucination - provides strict grounding. 
# Notice the CRITICAL language instruction: we need the answer in the user's native language.
# By ending the prompt mid-sentence with "Answer: [", we "force-feed" the model its first 
# characters, ensuring it starts exactly where we want it to, bypassing conversational filler.

PROMPT_TEMPLATE = """\
You are a precise, multilingual document assistant. Answer the question using ONLY the information \
in the provided document excerpts. Answer in a complete sentence, not just a number or single word. \
Do not use any outside knowledge.
CRITICAL: You must respond in the SAME LANGUAGE as the Question.
CRITICAL: Always answer in a complete sentence, not just a number or single word. \
For example, say 'The monthly rent is 1,350 EUR.' not just '1350'.

Format your response EXACTLY like this — no exceptions:
Answer: [your answer here]
Source_Quote: [the exact quote from the document that supports your answer]
[END]

If the answer is not found in the excerpts, respond exactly like this:
Answer: [The document does not contain information to answer this question.]
Source_Quote: [N/A]
[END]

Document Excerpts:
{chunks}

Question: {question}

Answer: ["""

# --- Core Function ----

def generate_answer(
    question: str,
    chunks: List[str],
    model_choice: str = "Global",
    max_tokens: int = DEFAULT_MAX_TOKENS,
    temperature: float = DEFAULT_TEMPERATURE 
) -> Dict[str, Any]: 
    """
    Sends the question + retrieved chunks to the local llama-server. 
    Returns a dictionary containing 'raw_output', 'model', 'success' boolean, and any 'error'.
    """
    
    # Format the incoming chunks into a neat, numbered list so the SLM can read them easily
    formatted_chunks = "\n\n".join(
        f"[Excerpt {i+1}]\n{chunk.strip()}"
        for i, chunk in enumerate(chunks)
    )

    # Inject our chunks and question into the prompt template
    prompt = PROMPT_TEMPLATE.format(
        chunks=formatted_chunks,
        question=question,
    )
    
    # Grab the correct URL (defaults to Global if a weird string is passed)
    url = SERVER_URLS.get(model_choice, SERVER_URLS["Global"])

    try:
        # Make the HTTP POST request to our local C++ server
        response = requests.post(
            url,
            json={
                "prompt": prompt,
                "n_predict": max_tokens,
                "temperature": temperature,
                "stop": ["[END]", "\nAnswer:"], 
                
            },
            timeout=120, # 2 min timeout in case the user's laptop is very slow (CPU-only)
        )
        # Raise an error if the server returned a 404, 500, etc.
        response.raise_for_status()
        
        # Extract the actual text generated by the model
        content = response.json().get("content", "").strip()

        # Reconstruct the full answer. Because our prompt ended with "Answer: [", 
        # the model's output doesn't include that part. We add it back here so the Regex parser works later.
        raw_output = f"Answer: [{content}"

        return {
            "raw_output": raw_output,
            "model": model_choice,
            "success": True,
            "error": None,
        }

    # Catch specific connection errors to give the user helpful debugging advice
    except requests.exceptions.ConnectionError:
        return {
            "raw_output": "",
            "model": model_choice,
            "success": False,
            "error": "Cannot connect to llama-server. Is it running in Terminal 1? Run: make server-global",
        }    
    except requests.exceptions.Timeout:
        return {
            "raw_output": "",
            "model": model_choice,
            "success": False,
            "error": "llama-server timed out. The model may be overloaded.",
        } 
    except Exception as e:
        return {
            "raw_output": "",
            "model": model_choice,
            "success": False,
            "error": f"Unexpected error: {str(e)}",
        }  

# --- Health Check ---

def check_server_health(model_choice: str = "Global") -> bool:
    """Returns True if llama-server is reachable and healthy."""
    try:
        response = requests.get(
            "http://localhost:8080/health",
            timeout=5
        )
        return response.json().get("status") == "ok"
    except Exception:
        return False  

# --- Quick Test (Execution Block) ---

if __name__ == "__main__":
    print("Testing generate.py (Make sure you ran 'make server-global' in another terminal!)...\n")

    # 1. Health Check
    if not check_server_health():
        print(" llama-server is not running.")
        print("Please open Terminal 1 and run: make server-global")
        exit(1)
    print(" Server is healthy!\n")

    # ------------------------------
    # TEST 1: Standard English QA
    # ------------------------------
    print("--- TEST 1: Standard English Extraction ---")
    test_chunks = [
        """The monthly rent is 1,200 euros, payable on the first of each month.
        A security deposit of 2,400 euros (two months rent) is required before
        move-in. The lease term is 12 months, beginning March 1, 2024."""
    ]
    test_question = "What is the security deposit amount?"
    print(f"Question: {test_question}")
    
    result = generate_answer(question=test_question, chunks=test_chunks)
    if result["success"]:
        print(f"Raw output:\n{result['raw_output']}\n")
    else:
        print(f"Generation failed: {result['error']}\n")

    # ---------------------------------------------------------
    # TEST 2: Multilingual Support (German context, Swahili query)
    # ---------------------------------------------------------
    print("--- TEST 2: Multilingual Support (H2 Testing) ---")
    german_chunk = """
    Die monatliche Miete beträgt 1.200 Euro und ist am ersten eines jeden Monats fällig.
    Die Kaution beträgt 2.400 Euro (zwei Monatsmieten) und ist vor dem Einzug zu zahlen.
    """
    swahili_question = "Kiwango cha dhamana ni kiasi gani?"  # "What is the deposit amount?"
    print(f"Question (Swahili): {swahili_question}")
    print(f"Context (German): {german_chunk.strip()}")

    result_multi = generate_answer(question=swahili_question, chunks=[german_chunk])
    if result_multi["success"]:
        print(f"Raw output:\n{result_multi['raw_output']}\n")
    else:
        print(f"Generation failed: {result_multi['error']}\n")

    # ---------------------------------------------------------
    # TEST 3: Anti-Hallucination (Answer NOT in document)
    # ---------------------------------------------------------
    print("--- TEST 3: Anti-Hallucination (Missing Info) ---")
    trick_question = "Are pets allowed in the apartment?"
    print(f"Question: {trick_question}")
    
    result_trick = generate_answer(question=trick_question, chunks=test_chunks) # Using the English chunks from Test 1
    if result_trick["success"]:
        print(f"Raw output:\n{result_trick['raw_output']}\n")
    else:
        print(f"Generation failed: {result_trick['error']}\n")