import logging

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import transformers

# Mute the harmless "UNEXPECTED position_ids" warning for a clean demo terminal
transformers.logging.set_verbosity_error()

logger = logging.getLogger(__name__)

MODEL_NAME = "MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7"

# Check for device availability once at module level (cheap operation)
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

# ---------------------------------------------------------------------------
# Lazy singleton — model loads on first nli_validation() call, not at import.
# This mirrors the embed.py pattern and prevents blocking Gradio startup.

_tokenizer = None
_model = None
_label_mapping = None


def _get_nli_model():
    """Load and cache the mDeBERTa NLI model on first call only."""
    global _tokenizer, _model, _label_mapping
    if _model is None:
        logger.info("NLI [1/3] loading model and tokenizer on %s (first call)...", device)
        _tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
        _model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME)
        _model.to(device)
        _model.eval()
        _label_mapping = _model.config.id2label
        logger.info("NLI model loaded on %s.", device)
    return _tokenizer, _model, _label_mapping


def nli_validation(
        list_premises: list,
        llm_answer: str
) -> list[dict]:
    """
    Check whether each retrieved source chunk supports the LLM's answer.


    NLI (Natural Language Inference) frames the problem as:
      Given a PREMISE (what the document says),
      does the HYPOTHESIS (what the model claimed) follow from it?

    Three possible relationships:
      entailment    = the premise logically supports the hypothesis  
      neutral       = the premise is unrelated or can't confirm      
      contradiction = the premise says the opposite of hypothesis    

    Args:
        list_premises:  Retrieved source chunks from the document.
                        These are the text passages your retriever found.
                        Typically 3 chunks per query.
        llm_answer:     The answer generated by the Tiny Aya model.

    Returns:
        List of result dicts, one per chunk:
        [
          {
            "premise":             "The monthly rent is 1,200 EUR.",
            "llm_answer":          "The rent is 1,200 EUR per month.",
            "nli_checking_result": "entailment",
            "confidence":          0.94
          },
          ...
        ]
    """

    tokenizer, model, label_mapping = _get_nli_model()
    logger.info("NLI [2/3] Start predicting input data")
    result = []
    for premise in list_premises:
        # Tokenization
        inputs = tokenizer(
            str(premise),       # premise  = what the document says
            str(llm_answer),    # hypothesis = what the LLM claimed
            return_tensors="pt",
            truncation=True,
            max_length=512,
        ).to(device)

        # Model prediction
        with torch.no_grad():
            logits = model(**inputs).logits
            probs = torch.softmax(logits, dim=-1).squeeze()
        
        predicted_idx = probs.argmax().item()
        predicted_label = label_mapping[predicted_idx]

        confidence = round(probs[predicted_idx].item(), 4)

        # CONFIDENCE THRESHOLD GUARD:
        # If the LLM generates hallucinated or irrelevant text, mDeBERTa gets
        # confused and may randomly guess "entailment" with low confidence,
        # producing a false green badge. Force neutral (yellow) if confidence
        # is below 0.60 so we never show a green badge we can't trust.
        if confidence < 0.60:
            predicted_label = "neutral"

        # Append results
        result.append({
            "premise": premise,
            "llm_answer": llm_answer,
            "nli_checking_result": predicted_label,
            "confidence": confidence
        })
        
    return result


def aggregate_verdict(nli_results: list[dict]):
    """
    The aggregation rules in order of priority:

      Rule 1: ANY entailment = entailment 
        The answer is supported by at least one chunk. That's enough.
        "Chunk 2 says the rent is 1200 EUR" confirms the answer even if
        chunks 1 and 3 are about completely different things.

      Rule 2: No entailment, but ANY contradiction = contradiction 
        No chunk supports the answer AND at least one chunk says something
        that directly conflicts with it. This is a likely hallucination.

      Rule 3: Everything neutral = neutral 
        No chunk confirms, no chunk contradicts. The model simply can't
        find grounding for this answer. Could be a retrieval miss.
    """

    logger.info("NLI [3/3] Aggregating the result")
    if not nli_results:
        # No chunks = nothing to check = can't confirm either way
        return "neutral"

    labels = [r["nli_checking_result"] for r in nli_results]

    # Rule 1: Most favourable label wins — any supporting chunk is enough
    if "entailment" in labels:
        return "entailment"

    # Rule 2: No support found + active contradiction = likely hallucination
    if "contradiction" in labels:
        return "contradiction"

    # Rule 3: No support, no contradiction = cannot confirm
    return "neutral"